#

pluginName = fr.n7.idm.layout Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Layout_type = Layout
_UI_Board_type = Board
_UI_Couche_type = Couche
_UI_CoucheExterne_type = Couche Externe
_UI_CoucheInterne_type = Couche Interne
_UI_ComposantPosition_type = Composant Position
_UI_Piste_type = Piste
_UI_Point_type = Point
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Layout_nom_feature = Nom
_UI_Layout_boards_feature = Boards
_UI_Layout_circuit_feature = Circuit
_UI_Board_nom_feature = Nom
_UI_Board_largeur_feature = Largeur
_UI_Board_hauteur_feature = Hauteur
_UI_Board_couches_feature = Couches
_UI_Couche_nom_feature = Nom
_UI_Couche_numero_feature = Numero
_UI_Couche_pistes_feature = Pistes
_UI_CoucheExterne_composants_feature = Composants
_UI_ComposantPosition_x_feature = X
_UI_ComposantPosition_y_feature = Y
_UI_ComposantPosition_rotation_feature = Rotation
_UI_ComposantPosition_instance_feature = Instance
_UI_Piste_nom_feature = Nom
_UI_Piste_largeur_feature = Largeur
_UI_Piste_points_feature = Points
_UI_Piste_connexion_feature = Connexion
_UI_Point_x_feature = X
_UI_Point_y_feature = Y
_UI_Unknown_feature = Unspecified

