/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.catalogue.xtext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import fr.n7.idm.catalogue.xtext.naming.CatalogueNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CatalogueRuntimeModule extends AbstractCatalogueRuntimeModule {
	@Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return CatalogueNameProvider.class;
    }
}
