/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.catalogue.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CatalogueStandaloneSetup extends CatalogueStandaloneSetupGenerated {

	public static void doSetup() {
		new CatalogueStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
