/**
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.catalogue.xtext.formatting2;

import com.google.inject.Inject;
import fr.n7.idm.catalogue.Catalogue;
import fr.n7.idm.catalogue.Composant;
import fr.n7.idm.catalogue.Contrainte;
import fr.n7.idm.catalogue.Empreinte;
import fr.n7.idm.catalogue.Port;
import fr.n7.idm.catalogue.xtext.services.CatalogueGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class CatalogueFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private CatalogueGrammarAccess _catalogueGrammarAccess;

  protected void _format(final Catalogue catalogue, @Extension final IFormattableDocument document) {
    EList<Composant> _composants = catalogue.getComposants();
    for (final Composant composant : _composants) {
      document.<Composant>format(composant);
    }
  }

  protected void _format(final Composant composant, @Extension final IFormattableDocument document) {
    EList<Port> _ports = composant.getPorts();
    for (final Port port : _ports) {
      document.<Port>format(port);
    }
    document.<Empreinte>format(composant.getEmpreinte());
    EList<Contrainte> _contraintes = composant.getContraintes();
    for (final Contrainte contrainte : _contraintes) {
      document.<Contrainte>format(contrainte);
    }
  }

  public void format(final Object catalogue, final IFormattableDocument document) {
    if (catalogue instanceof XtextResource) {
      _format((XtextResource)catalogue, document);
      return;
    } else if (catalogue instanceof Catalogue) {
      _format((Catalogue)catalogue, document);
      return;
    } else if (catalogue instanceof Composant) {
      _format((Composant)catalogue, document);
      return;
    } else if (catalogue instanceof EObject) {
      _format((EObject)catalogue, document);
      return;
    } else if (catalogue == null) {
      _format((Void)null, document);
      return;
    } else if (catalogue != null) {
      _format(catalogue, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(catalogue, document).toString());
    }
  }
}
