<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="layout" nsURI="http://www.example.org/layout" nsPrefix="layout">
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boards" upperBound="-1"
        eType="#//Board" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="circuit" eType="ecore:EClass ../../fr.n7.idm.netlist/model/netlist.ecore#//Circuit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hauteur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="couches" lowerBound="1"
        upperBound="-1" eType="#//Couche" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Couche" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pistes" upperBound="-1"
        eType="#//Piste" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoucheExterne" eSuperTypes="#//Couche">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonChevauchement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composants" upperBound="-1"
        eType="#//ComposantPosition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoucheInterne" eSuperTypes="#//Couche"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComposantPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass ../../fr.n7.idm.netlist/model/netlist.ecore#//InstanceComposant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Piste">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" lowerBound="2"
        upperBound="-1" eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connexion" eType="ecore:EClass ../../fr.n7.idm.netlist/model/netlist.ecore#//Connexion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
