/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1.impl;

import fr.n7.pDL1.PDL1Package;
import fr.n7.pDL1.Resource;
import fr.n7.pDL1.UsageResource;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Usage Resource</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.impl.UsageResourceImpl#getResource <em>Resource</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.UsageResourceImpl#getUsageQuantity <em>Usage Quantity</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.UsageResourceImpl#getUsageTime <em>Usage Time</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UsageResourceImpl extends MinimalEObjectImpl.Container implements UsageResource
{
  /**
   * The cached value of the '{@link #getResource() <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResource()
   * @generated
   * @ordered
   */
  protected Resource resource;

  /**
   * The default value of the '{@link #getUsageQuantity() <em>Usage Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsageQuantity()
   * @generated
   * @ordered
   */
  protected static final int USAGE_QUANTITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getUsageQuantity() <em>Usage Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsageQuantity()
   * @generated
   * @ordered
   */
  protected int usageQuantity = USAGE_QUANTITY_EDEFAULT;

  /**
   * The default value of the '{@link #getUsageTime() <em>Usage Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsageTime()
   * @generated
   * @ordered
   */
  protected static final int USAGE_TIME_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getUsageTime() <em>Usage Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsageTime()
   * @generated
   * @ordered
   */
  protected int usageTime = USAGE_TIME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UsageResourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.USAGE_RESOURCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Resource getResource()
  {
    if (resource != null && resource.eIsProxy())
    {
      InternalEObject oldResource = (InternalEObject)resource;
      resource = (Resource)eResolveProxy(oldResource);
      if (resource != oldResource)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.USAGE_RESOURCE__RESOURCE, oldResource, resource));
      }
    }
    return resource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Resource basicGetResource()
  {
    return resource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResource(Resource newResource)
  {
    Resource oldResource = resource;
    resource = newResource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.USAGE_RESOURCE__RESOURCE, oldResource, resource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getUsageQuantity()
  {
    return usageQuantity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUsageQuantity(int newUsageQuantity)
  {
    int oldUsageQuantity = usageQuantity;
    usageQuantity = newUsageQuantity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.USAGE_RESOURCE__USAGE_QUANTITY, oldUsageQuantity, usageQuantity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getUsageTime()
  {
    return usageTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUsageTime(int newUsageTime)
  {
    int oldUsageTime = usageTime;
    usageTime = newUsageTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.USAGE_RESOURCE__USAGE_TIME, oldUsageTime, usageTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL1Package.USAGE_RESOURCE__RESOURCE:
        if (resolve) return getResource();
        return basicGetResource();
      case PDL1Package.USAGE_RESOURCE__USAGE_QUANTITY:
        return getUsageQuantity();
      case PDL1Package.USAGE_RESOURCE__USAGE_TIME:
        return getUsageTime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL1Package.USAGE_RESOURCE__RESOURCE:
        setResource((Resource)newValue);
        return;
      case PDL1Package.USAGE_RESOURCE__USAGE_QUANTITY:
        setUsageQuantity((Integer)newValue);
        return;
      case PDL1Package.USAGE_RESOURCE__USAGE_TIME:
        setUsageTime((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.USAGE_RESOURCE__RESOURCE:
        setResource((Resource)null);
        return;
      case PDL1Package.USAGE_RESOURCE__USAGE_QUANTITY:
        setUsageQuantity(USAGE_QUANTITY_EDEFAULT);
        return;
      case PDL1Package.USAGE_RESOURCE__USAGE_TIME:
        setUsageTime(USAGE_TIME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.USAGE_RESOURCE__RESOURCE:
        return resource != null;
      case PDL1Package.USAGE_RESOURCE__USAGE_QUANTITY:
        return usageQuantity != USAGE_QUANTITY_EDEFAULT;
      case PDL1Package.USAGE_RESOURCE__USAGE_TIME:
        return usageTime != USAGE_TIME_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (UsageQuantity: ");
    result.append(usageQuantity);
    result.append(", UsageTime: ");
    result.append(usageTime);
    result.append(')');
    return result.toString();
  }

} //UsageResourceImpl
