/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.catalogue.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class CatalogueIdeModule extends AbstractCatalogueIdeModule {
}
