/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.catalogue.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.idm.catalogue.xtext.CatalogueRuntimeModule;
import fr.n7.idm.catalogue.xtext.CatalogueStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CatalogueIdeSetup extends CatalogueStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CatalogueRuntimeModule(), new CatalogueIdeModule()));
	}
	
}
