/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.catalogue.xtext.formatting2

import com.google.inject.Inject
import fr.n7.idm.catalogue.Catalogue
import fr.n7.idm.catalogue.Composant
import fr.n7.idm.catalogue.xtext.services.CatalogueGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class CatalogueFormatter extends AbstractFormatter2 {
	
	@Inject extension CatalogueGrammarAccess

	def dispatch void format(Catalogue catalogue, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (composant : catalogue.composants) {
			composant.format
		}
	}

	def dispatch void format(Composant composant, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (port : composant.ports) {
			port.format
		}
		composant.empreinte.format
		for (contrainte : composant.contraintes) {
			contrainte.format
		}
	}
	
	// TODO: implement for Empreinte, ContrainteEt, ContrainteOu, ContrainteNon
}
