#

pluginName = fr.n7.idm.catalogue Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Catalogue_type = Catalogue
_UI_Composant_type = Composant
_UI_Port_type = Port
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Catalogue_composants_feature = Composants
_UI_Composant_nom_feature = Nom
_UI_Composant_fabricant_feature = Fabricant
_UI_Composant_ports_feature = Ports
_UI_Unknown_feature = Unspecified

_UI_Empreinte_type = Empreinte
_UI_PositionPort_type = Position Port
_UI_Contrainte_type = Contrainte
_UI_ContrainteLogique_type = Contrainte Logique
_UI_ContrainteEt_type = Contrainte Et
_UI_ContrainteOu_type = Contrainte Ou
_UI_ContrainteNon_type = Contrainte Non
_UI_ContrainteGeometrique_type = Contrainte Geometrique
_UI_ContrainteRedondance_type = Contrainte Redondance
_UI_Composant_description_feature = Description
_UI_Composant_empreinte_feature = Empreinte
_UI_Composant_contraintes_feature = Contraintes
_UI_Port_nom_feature = Nom
_UI_Port_type_feature = Type
_UI_Empreinte_largeur_feature = Largeur
_UI_Empreinte_hauteur_feature = Hauteur
_UI_Empreinte_positionsPort_feature = Positions Port
_UI_PositionPort_x_feature = X
_UI_PositionPort_y_feature = Y
_UI_PositionPort_port_feature = Port
_UI_ContrainteEt_operands_feature = Operands
_UI_ContrainteOu_operands_feature = Operands
_UI_ContrainteNon_operand_feature = Operand
_UI_ContrainteGeometrique_distanceMin_feature = Distance Min
_UI_ContrainteGeometrique_distanceMax_feature = Distance Max
_UI_ContrainteGeometrique_zoneInterdite_feature = Zone Interdite
_UI_ContrainteRedondance_nombreMinimum_feature = Nombre Minimum
