<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petriNet" nsURI="platform:/resource/fr.n7.petriNet/PetriNet.ecore"
    nsPrefix="petriNet">
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
        eType="#//Place" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcs" upperBound="-1" eType="#//Arc"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialMarketing" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcsSortants" upperBound="-1"
        eType="#//ArcPlaceTransition" eOpposite="#//ArcPlaceTransition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcsEntrants" upperBound="-1"
        eType="#//ArcTransitionPlace" eOpposite="#//ArcTransitionPlace/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcsEntrants" upperBound="-1"
        eType="#//ArcPlaceTransition" eOpposite="#//ArcPlaceTransition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcsSortants" upperBound="-1"
        eType="#//ArcTransitionPlace" eOpposite="#//ArcTransitionPlace/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcPlaceTransition" eSuperTypes="#//Arc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Place" eOpposite="#//Place/arcsSortants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Transition" eOpposite="#//Transition/arcsEntrants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcTransitionPlace" eSuperTypes="#//Arc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Transition" eOpposite="#//Transition/arcsSortants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Place" eOpposite="#//Place/arcsEntrants"/>
  </eClassifiers>
</ecore:EPackage>
