/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Usage Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.UsageResource#getResource <em>Resource</em>}</li>
 *   <li>{@link fr.n7.pDL1.UsageResource#getUsageQuantity <em>Usage Quantity</em>}</li>
 *   <li>{@link fr.n7.pDL1.UsageResource#getUsageTime <em>Usage Time</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getUsageResource()
 * @model
 * @generated
 */
public interface UsageResource extends EObject
{
  /**
   * Returns the value of the '<em><b>Resource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' reference.
   * @see #setResource(Resource)
   * @see fr.n7.pDL1.PDL1Package#getUsageResource_Resource()
   * @model
   * @generated
   */
  Resource getResource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.UsageResource#getResource <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource</em>' reference.
   * @see #getResource()
   * @generated
   */
  void setResource(Resource value);

  /**
   * Returns the value of the '<em><b>Usage Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usage Quantity</em>' attribute.
   * @see #setUsageQuantity(int)
   * @see fr.n7.pDL1.PDL1Package#getUsageResource_UsageQuantity()
   * @model
   * @generated
   */
  int getUsageQuantity();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.UsageResource#getUsageQuantity <em>Usage Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Usage Quantity</em>' attribute.
   * @see #getUsageQuantity()
   * @generated
   */
  void setUsageQuantity(int value);

  /**
   * Returns the value of the '<em><b>Usage Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usage Time</em>' attribute.
   * @see #setUsageTime(int)
   * @see fr.n7.pDL1.PDL1Package#getUsageResource_UsageTime()
   * @model
   * @generated
   */
  int getUsageTime();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.UsageResource#getUsageTime <em>Usage Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Usage Time</em>' attribute.
   * @see #getUsageTime()
   * @generated
   */
  void setUsageTime(int value);

} // UsageResource
